export const projects = [
  {
    title: 'P.E.E.R.Program ATX',
    description: "This site is for a small company in Austin for a treatment program to help addicts. They needed a website for their business. Customers could find them online and send a message if that interested them. It was my first product, which was finished in 2019. It is based on Vue.",
    image: '/images/vue.png',
    tags: ['Vue', 'JavaScript'],
    visit: 'https://peerprogramatx.com/',
    id: 0,
  },
  {
    title: 'Willamette Bearcats',
    description: "This website is designed to show sports pictures. In other words, it's the photograph library. You can search for exciting photographs. On this website, I tried to create an intelligent and clean environment. As you can see, it is very simple and looks quite regular. It is based on React.",
    image: '/images/sports_photos.png',
    tags: ['React', 'JavaScript'],
    visit: 'https://photos.wubearcats.com/',
    id: 1,
  },
  {
    title: 'Josephine House',
    description: "It's a tiny restaurant in Austin. The design of the site is not great, but it provides convenience. Guests can order from this website. Using this site, the restaurant import was increased 1.5 times.This site based on WordPress.",
    image: '/images/josephine_house.png',
    tags: ['WordPress', 'PHP'],
    visit: 'https://josephineofaustin.com/',
    id: 2,
  },
  {
    title: 'Komé',
    description: "That's a small restaurant in Austin. This website provides food listing and advertising. This website looks like simple and clean. Customers can join other restaurants through this site. They can find food they want details. It is based on WordPress.",
    image: '/images/Kome_Sushi.png',
    tags: ['WordPress', 'PHP'],
    visit: 'https://www.kome-austin.com/',
    id: 3,
  },
  {
    title: 'Marlin Medical Assistance',
    description: "That's a small restaurant in Austin. This website provides food listing and advertising. This website looks like simple and clean. Customers can join other restaurants through this site. They can find food they want details. It is based on WordPress.",
    image: '/images/Marlin.png',
    tags: ['React', 'Laravel', 'MySQL'],
    visit: 'https://marlinmedicalassistance.com/',
    id: 4,
  },
  {
    title: 'Capitol School of Austin',
    description: "That's a small restaurant in Austin. This website provides food listing and advertising. This website looks like simple and clean. Customers can join other restaurants through this site. They can find food they want details. It is based on WordPress.",
    image: '/images/capital_school.png',
    tags: ['WordPress'],
    visit: 'https://www.capitolschool.com/',
    id: 5,
  },
  {
    title: 'McKinsey',
    description: "That's a small restaurant in Austin. This website provides food listing and advertising. This website looks like simple and clean. Customers can join other restaurants through this site. They can find food they want details. It is based on WordPress.",
    image: '/images/Mc_kinsey.png',
    tags: ['React', 'Node.js', 'Express', 'MongoDB'],
    visit: 'https://www.mckinsey.com/',
    id: 6,
  },
  {
    title: 'Blossöm Records',
    description: "That's a small restaurant in Austin. This website provides food listing and advertising. This website looks like simple and clean. Customers can join other restaurants through this site. They can find food they want details. It is based on WordPress.",
    image: '/images/herald.png',
    tags: ['WordPress', 'PHP'],
    visit: 'https://blossomrecs.com/',
    id: 7,
  },
];

export const TimeLineData = [
  { year: 2018, text: 'Started my journey', },
  { year: 2019, text: 'Worked as a freelance developer', },
  { year: 2020, text: 'Founded JavaScript Mastery', },
  { year: 2021, text: 'Shared my projects with the world', },
  { year: 2022, text: 'Started my own platform', },
];